### ISSUE TITLE
Don't find the right AGPF key instead WPA tester find it

### ISSUE THREAD

**Issue by zoomx** [routerkeygen/routerkeygenAndroid#11]
I tested this app against my AGPF. This is not my original device because the original broken and was replaced by Telecom. All configurations (the original SSID and key asnd many others) where copied from the broken AGPF to the new AGPF. I believe that only MAC address changed but I can't confirm it.
WPA tester
http://carlomandroid.wordpress.com/download-wpa-tester/
can find the right key instead routerkeygenAndroid finds another key that is not the default key of the new AGPF that is printed on a stick on the bottom.

**Comment by shakre** [comment]
5e6067f

**Comment by shakre** [comment]
#11

**Comment by shakre** [comment]
saqr777
