### ISSUE TITLE
I can't download Dictionary for Thomson

### ISSUE THREAD

**Issue by arojoal** [routerkeygen/routerkeygenAndroid#18]
Working with version 3.12.0 when I click on "Download dictionary" it show a message telling that dictionary's version is too advanced for this version. Please download latest version"

**Comment by ruiaraujo** [comment]
I can't replicate that on my Nexus 5.

What phone do you have?

**Comment by shakre** [comment]
#11

**Comment by shakre** [comment]
#18

**Comment by shakre** [comment]
3.12.0

**Comment by shakre** [comment]
Htc

**Comment by shakre** [comment]
#18

**Comment by arojoal** [comment]
Nexus 5

**Comment by shakre** [comment]
saqr83936@gmail.com

**Comment by shakre** [comment]
https://github.com/shakre

**Comment by shakre** [comment]
#18

**Comment by ruiaraujo** [comment]
You don't really need a dictionary because the native algorithm is fast enough to do it.

I will try to replicate it but until it has worked flawlessly.

Can you add more details on what you did, how did you upgrad?

**Comment by ruiaraujo** [comment]
@arojoal Have you tried with the latest version?

**Comment by arojoal** [comment]
Yes. I send a screenshot.

Alex Rojo

**Comment by alinoyudhi** [comment]
Hi. I am using lenovo A7000. When I try to use router keygen, should I install Penetrate Pro as well?
I can't use it. Only the red light UNSUPPORT.
Please help me
Thanks in advance.
Alino

**Comment by ruiaraujo** [comment]
@alinoyudhi don't hijack issue threads. 

@arojoal Does still happen with the latest version?

**Comment by alinoyudhi** [comment]
Hi Rui,

Can you help me? I can't use it.

I already upgrade with the latest version.

Something wrong with my installation?


Attach as screenshoot.

Thanks in advance

Alino

Sent from Yahoo Mail on Android

**Comment by ruiaraujo** [comment]
any updates?

**Comment by ruiaraujo** [comment]
Closed by lack of responses.
