### ISSUE TITLE
no TP-LINk support

### ISSUE THREAD

**Issue by j-brandstetter** [routerkeygen/routerkeygenAndroid#19]
The changelog of v3.12.0 (05/05/15) says "New: tplink algorithm", but TP-LINK is not supportet
You can see it on the attached screenshots.
![screenshot_2015-05-14-20-39-34](https://cloud.githubusercontent.com/assets/12429752/7639383/bfa5d93c-fa7b-11e4-8b17-7027ff4d1c9a.png)

![screenshot_2015-05-14-20-40-27](https://cloud.githubusercontent.com/assets/12429752/7639385/c3975d22-fa7b-11e4-80b9-2bd74d55e376.png)

**Comment by ruiaraujo** [comment]
Indeed that one is unsupported, it is just for one very specific model form TP-LINK.
