### ISSUE TITLE
can't install the app in a Moto G XT1063 (2nd Gen)

### ISSUE THREAD

**Issue by CarlosMv** [routerkeygen/routerkeygenAndroid#23]
Hi, I downloaded the app but the cell doesn't allow the installation is it normal that mistake?

**Comment by ruiaraujo** [comment]
@CarlosMv try installing from here:
https://play.google.com/store/apps/details?id=io.github.routerkeygen

**Comment by CarlosMv** [comment]
Thaks for the help @ruiaraujo
