### ISSUE TITLE
Lg g2 crashes and hangs after using it

### ISSUE THREAD

**Issue by giannino** [routerkeygen/routerkeygenAndroid#24]
It happened months ago and today again: the phone resets then becomes unusable, slow, hot, battery drain.
in the meantime i updated to lollipop and last version of Akeygen

**Comment by ruiaraujo** [comment]
Did you use the "try the keys" feature?

Or just normal scanning?

**Comment by JeroenPleysier** [comment]
I think you might got the wrong email address? I don’t know what this is about…






Verzonden met Windows Mail





Van: giannino
Verzonden: ‎maandag‎ ‎22‎ ‎juni‎ ‎2015 ‎20‎:‎40
Aan: routerkeygen/routerkeygenAndroid





It happened months ago and today again: the phone resets then becomes unusable, slow, hot, battery drain.
in the meantime i updated to lollipop and last version of Akeygen

**Comment by giannino** [comment]
yestyerday with try the keys, I then restored hotspot list (wpasupplicant)
with titanium and now its' ok

**Comment by giannino** [comment]
your'e in a github list

**Comment by ruiaraujo** [comment]
@giannino this is probably a bug with LG since I am just using APIs.

I am not really sure what is happening.

**Comment by giannino** [comment]
Yes, You Mary be right, i remember the same thing happening for other apps
who managed Wi-Fi

**Comment by ruiaraujo** [comment]
I am closing this issue for now since I don't think there is something we can do here.

if you're using a third party ROM, that might be a cause.

**Comment by giannino** [comment]
No, stock kitkat and Lollipopj

**Comment by Tiinabiie** [comment]
#24
