### ISSUE TITLE
Release new version with UPC support

### ISSUE THREAD

**Issue by prusnak** [routerkeygen/routerkeygenAndroid#36]
$title says it all. Also, please, upload to Google Play. Thanks!

**Comment by vlinhart** [comment]
:+1:

**Comment by TuxCoder** [comment]
+1

**Comment by blackwat3r** [comment]
how about also giving blasty proper credit for making the upc support possible since it is based on his code

**Comment by Lexus89** [comment]
+1 for UPC support

**Comment by domdorn** [comment]
+1

**Comment by Xeleron** [comment]
And maybe use the modified upc_keys.c source? https://github.com/spaze/upc_keys-lambda/blob/master/upc_keys.c

**Comment by prusnak** [comment]
As it seems the upstream does not care, here is the fork with UPC update:

https://github.com/yolosec/routerkeygenAndroid

and Appstore link:

https://play.google.com/store/apps/details?id=net.yolosec.routerkeygen2

**Comment by hackrid** [comment]
lokking at the repos you linked, it seems like this repo here is dead (?)

**Comment by ruiaraujo** [comment]
It is not dead, just the next release accumulated quite a bit of code that
needs to be properly tested.

I think I will be able to do it in the next two weeks.

A seg, 4/07/2016, 14:35, hackrid <notifications@github.com> escreveu:

**Comment by TuxCoder** [comment]
@ruiaraujo nice to hear that, what do you think about some nice nightly build from travis-ci or some other service?
I have build a version with some gradle patches https://www.git.o-g.at/tuxcoder/routerkeygenAndroid
This version builds and works fine for me (Android 6, MIUI ), but I have also done some ads and tracking modification for private usage.
Hopefully this helps you a bit.

**Comment by Velociraptor85** [comment]
bump? @ruiaraujo

**Comment by ruiaraujo** [comment]
Done.
