### ISSUE TITLE
Version 4.0.2 does not run without google

### ISSUE THREAD

**Issue by pidiet** [routerkeygen/routerkeygenAndroid#46]
Hello,

first a very warm thank you for creating and maintaining this App. It's very usefull and it's really nice to see this one on github.

I'm a happy google-free (no gapps) phone user and sadly the most recent version (4.0.2) does not work on my phone.
The version 3.15 is working without problems (seems there is no gapps requirement)

Is it possible to get a 4.x release which works without gapps? Would be really great!

**Comment by pidiet** [comment]
I think I tracked it down. It's a Ad Library which makes the app incompatible with all google free phones world wide.

Very sad.

**Comment by ruiaraujo** [comment]
Feel free to add variant that does not require it. I would merge such a PR.

**Comment by rradar** [comment]
@ruiaraujo thank's for your reply. Sadly I don't have any coding skills to write code and do a PR with this.

Anyway thank's a lot having this software available as FOSS!
