### ISSUE TITLE
Router Keygen - All WiFi networks support?

### ISSUE THREAD

**Issue by Name277** [routerkeygen/routerkeygenAndroid#51]
One of my friends that used some kind of version of router keygen was able to crack every WiFi network within a second as he was walking around using this app, how exactly is this possible? Is there some kind of modified dictionary files that supports every WiFi network right now? The passwords were showing under the MAC address of every network instead of tapping to display it. Can someone explain how that works? Thanks.

**Comment by ph4r05** [comment]
Tldr - routers often use deterministic passphrase generation based on public parameters such as BSSID or SSID
